export interface ProfessionData {
  slug: string
  title: string
  category: string
  medianSalary: number
  p25Salary: number
  p75Salary: number
  p90Salary: number
  entryLevel: number
  seniorLevel: number
  topStates: string[]
  topCities: string[]
  jobGrowth: number
  education: string
  desc: string
}

export const PROFESSIONS: ProfessionData[] = [
  // Technology
  {
    slug: 'software-engineer',
    title: 'Software Engineer',
    category: 'Technology',
    medianSalary: 130160,
    p25Salary: 99000,
    p75Salary: 168000,
    p90Salary: 220000,
    entryLevel: 85000,
    seniorLevel: 185000,
    topStates: ['california', 'washington', 'new-york', 'texas', 'massachusetts'],
    topCities: ['San Francisco', 'Seattle', 'New York City'],
    jobGrowth: 25,
    education: "Bachelor's in Computer Science or related field",
    desc: "Software engineers design, develop, and maintain applications and systems across every industry. The BLS projects 25% job growth through 2032 — far faster than average — driven by cloud computing, AI integration, and ongoing digital transformation across sectors.",
  },
  {
    slug: 'data-scientist',
    title: 'Data Scientist',
    category: 'Technology',
    medianSalary: 108020,
    p25Salary: 84000,
    p75Salary: 145000,
    p90Salary: 195000,
    entryLevel: 72000,
    seniorLevel: 165000,
    topStates: ['california', 'washington', 'new-york', 'massachusetts', 'virginia'],
    topCities: ['San Francisco', 'New York City', 'Seattle'],
    jobGrowth: 35,
    education: "Master's or PhD in Statistics, Computer Science, or Mathematics",
    desc: "Data scientists extract actionable insights from large datasets using statistical analysis, machine learning, and data visualization. The role commands some of the fastest salary growth in tech, with senior practitioners at major tech firms routinely clearing $200,000 in total compensation.",
  },
  {
    slug: 'machine-learning-engineer',
    title: 'Machine Learning Engineer',
    category: 'Technology',
    medianSalary: 158000,
    p25Salary: 125000,
    p75Salary: 200000,
    p90Salary: 270000,
    entryLevel: 105000,
    seniorLevel: 230000,
    topStates: ['california', 'washington', 'new-york', 'massachusetts', 'texas'],
    topCities: ['San Francisco', 'Seattle', 'New York City'],
    jobGrowth: 40,
    education: "Master's in Computer Science, AI, or related field",
    desc: "Machine learning engineers build and deploy the models that power AI products, bridging the gap between research and production systems. Demand has surged with the generative AI boom, pushing median total compensation above $200,000 at major technology companies.",
  },
  {
    slug: 'devops-engineer',
    title: 'DevOps Engineer',
    category: 'Technology',
    medianSalary: 125000,
    p25Salary: 98000,
    p75Salary: 158000,
    p90Salary: 205000,
    entryLevel: 80000,
    seniorLevel: 175000,
    topStates: ['california', 'washington', 'texas', 'new-york', 'virginia'],
    topCities: ['Seattle', 'San Francisco', 'Austin'],
    jobGrowth: 21,
    education: "Bachelor's in Computer Science or equivalent experience",
    desc: "DevOps engineers manage the CI/CD pipelines, infrastructure automation, and cloud environments that keep software companies running. Cloud-native adoption at enterprises and the shift to microservices have made this one of the most in-demand technical roles of the decade.",
  },
  {
    slug: 'cloud-architect',
    title: 'Cloud Architect',
    category: 'Technology',
    medianSalary: 155000,
    p25Salary: 125000,
    p75Salary: 195000,
    p90Salary: 240000,
    entryLevel: 105000,
    seniorLevel: 210000,
    topStates: ['california', 'washington', 'virginia', 'texas', 'new-york'],
    topCities: ['Seattle', 'San Francisco', 'Washington DC'],
    jobGrowth: 28,
    education: "Bachelor's in Computer Science plus cloud certifications (AWS, Azure, GCP)",
    desc: "Cloud architects design enterprise-scale infrastructure on AWS, Azure, and Google Cloud, setting the technical direction for organizations migrating off on-premise systems. The role commands a significant salary premium over generalist software engineers given the breadth of domain expertise required.",
  },
  {
    slug: 'cybersecurity-analyst',
    title: 'Cybersecurity Analyst',
    category: 'Technology',
    medianSalary: 112000,
    p25Salary: 88000,
    p75Salary: 142000,
    p90Salary: 180000,
    entryLevel: 70000,
    seniorLevel: 160000,
    topStates: ['virginia', 'california', 'texas', 'maryland', 'new-york'],
    topCities: ['Washington DC', 'San Francisco', 'Dallas'],
    jobGrowth: 32,
    education: "Bachelor's in Cybersecurity or Computer Science; CISSP, CEH certifications valued",
    desc: "Cybersecurity analysts protect networks, systems, and data from breaches, monitoring for threats and responding to incidents. The BLS projects 32% job growth through 2032 as ransomware attacks and data breaches continue to accelerate across both private and public sectors.",
  },
  {
    slug: 'product-manager',
    title: 'Product Manager',
    category: 'Technology',
    medianSalary: 140000,
    p25Salary: 108000,
    p75Salary: 180000,
    p90Salary: 230000,
    entryLevel: 90000,
    seniorLevel: 200000,
    topStates: ['california', 'washington', 'new-york', 'texas', 'massachusetts'],
    topCities: ['San Francisco', 'New York City', 'Seattle'],
    jobGrowth: 10,
    education: "Bachelor's degree; MBA common at senior levels",
    desc: "Product managers set the vision and roadmap for software products, working at the intersection of engineering, design, and business. At top-tier technology companies, total compensation packages including stock regularly exceed $250,000 for senior PMs.",
  },
  {
    slug: 'ux-designer',
    title: 'UX Designer',
    category: 'Technology',
    medianSalary: 99000,
    p25Salary: 76000,
    p75Salary: 130000,
    p90Salary: 165000,
    entryLevel: 58000,
    seniorLevel: 145000,
    topStates: ['california', 'new-york', 'washington', 'texas', 'illinois'],
    topCities: ['San Francisco', 'New York City', 'Seattle'],
    jobGrowth: 3,
    education: "Bachelor's in Design, HCI, or related field; portfolio required",
    desc: "UX designers research user behavior and craft interfaces that make complex software intuitive and accessible. While the field has seen some softening in job openings since 2023, experienced designers at major tech companies and financial services firms remain highly compensated.",
  },
  {
    slug: 'frontend-developer',
    title: 'Frontend Developer',
    category: 'Technology',
    medianSalary: 118000,
    p25Salary: 90000,
    p75Salary: 152000,
    p90Salary: 195000,
    entryLevel: 72000,
    seniorLevel: 170000,
    topStates: ['california', 'washington', 'new-york', 'texas', 'illinois'],
    topCities: ['San Francisco', 'New York City', 'Seattle'],
    jobGrowth: 16,
    education: "Bachelor's in Computer Science or self-taught with strong portfolio",
    desc: "Frontend developers build the user-facing layer of web applications using JavaScript frameworks like React, Vue, and Angular. The role increasingly overlaps with full-stack development as serverless architectures blur traditional boundaries between client and server code.",
  },
  {
    slug: 'backend-developer',
    title: 'Backend Developer',
    category: 'Technology',
    medianSalary: 125000,
    p25Salary: 96000,
    p75Salary: 160000,
    p90Salary: 205000,
    entryLevel: 78000,
    seniorLevel: 178000,
    topStates: ['california', 'washington', 'new-york', 'texas', 'illinois'],
    topCities: ['San Francisco', 'Seattle', 'New York City'],
    jobGrowth: 18,
    education: "Bachelor's in Computer Science or equivalent experience",
    desc: "Backend developers architect and maintain the server-side logic, databases, and APIs that power modern applications. Specializations in distributed systems, database optimization, and high-availability architecture command significant salary premiums.",
  },
  {
    slug: 'full-stack-developer',
    title: 'Full Stack Developer',
    category: 'Technology',
    medianSalary: 122000,
    p25Salary: 93000,
    p75Salary: 158000,
    p90Salary: 200000,
    entryLevel: 75000,
    seniorLevel: 175000,
    topStates: ['california', 'washington', 'new-york', 'texas', 'georgia'],
    topCities: ['San Francisco', 'Austin', 'New York City'],
    jobGrowth: 17,
    education: "Bachelor's in Computer Science or equivalent coding bootcamp plus experience",
    desc: "Full stack developers handle both frontend and backend development, making them versatile assets for startups and mid-size companies that need engineers who can ship features end-to-end. The role typically commands a slight discount to senior specialists in either discipline.",
  },
  {
    slug: 'database-administrator',
    title: 'Database Administrator',
    category: 'Technology',
    medianSalary: 101000,
    p25Salary: 78000,
    p75Salary: 132000,
    p90Salary: 165000,
    entryLevel: 62000,
    seniorLevel: 148000,
    topStates: ['california', 'texas', 'new-york', 'virginia', 'illinois'],
    topCities: ['Washington DC', 'New York City', 'Chicago'],
    jobGrowth: 9,
    education: "Bachelor's in Computer Science; Oracle, SQL Server certifications valuable",
    desc: "Database administrators design, implement, and maintain the database systems that store an organization's critical data. Cloud database migration projects have kept demand robust, though the market for pure on-premise DBA roles has shrunk as managed cloud services handle more routine administration.",
  },
  {
    slug: 'it-manager',
    title: 'IT Manager',
    category: 'Technology',
    medianSalary: 164000,
    p25Salary: 128000,
    p75Salary: 205000,
    p90Salary: 250000,
    entryLevel: 100000,
    seniorLevel: 220000,
    topStates: ['california', 'virginia', 'new-york', 'texas', 'washington'],
    topCities: ['Washington DC', 'San Francisco', 'New York City'],
    jobGrowth: 15,
    education: "Bachelor's in Computer Science or IT; MBA or MBA common at VP level",
    desc: "IT managers oversee technology departments, managing teams, budgets, vendor relationships, and strategic technology planning. The role spans industries from finance to healthcare, with compensation varying significantly based on the organization's technology complexity and headcount.",
  },
  {
    slug: 'data-engineer',
    title: 'Data Engineer',
    category: 'Technology',
    medianSalary: 132000,
    p25Salary: 103000,
    p75Salary: 168000,
    p90Salary: 215000,
    entryLevel: 85000,
    seniorLevel: 185000,
    topStates: ['california', 'washington', 'new-york', 'texas', 'massachusetts'],
    topCities: ['San Francisco', 'Seattle', 'New York City'],
    jobGrowth: 30,
    education: "Bachelor's in Computer Science, Statistics, or Mathematics",
    desc: "Data engineers build and maintain the pipelines that move, transform, and store data for analytics and machine learning applications. The explosion of real-time streaming architectures using tools like Apache Kafka and Spark has made experienced data engineers among the most sought-after technical hires.",
  },
  {
    slug: 'mobile-developer',
    title: 'Mobile Developer',
    category: 'Technology',
    medianSalary: 120000,
    p25Salary: 92000,
    p75Salary: 155000,
    p90Salary: 198000,
    entryLevel: 74000,
    seniorLevel: 170000,
    topStates: ['california', 'washington', 'new-york', 'texas', 'florida'],
    topCities: ['San Francisco', 'New York City', 'Austin'],
    jobGrowth: 14,
    education: "Bachelor's in Computer Science; iOS (Swift) or Android (Kotlin) specialization",
    desc: "Mobile developers build native and cross-platform applications for iOS and Android devices, increasingly using frameworks like React Native and Flutter to target both platforms from a single codebase. Consumer app revenue exceeding $500 billion annually ensures sustained demand.",
  },
  {
    slug: 'qa-engineer',
    title: 'QA Engineer',
    category: 'Technology',
    medianSalary: 98000,
    p25Salary: 76000,
    p75Salary: 128000,
    p90Salary: 162000,
    entryLevel: 60000,
    seniorLevel: 140000,
    topStates: ['california', 'washington', 'texas', 'new-york', 'colorado'],
    topCities: ['San Francisco', 'Seattle', 'Austin'],
    jobGrowth: 6,
    education: "Bachelor's in Computer Science or related field; ISTQB certification valuable",
    desc: "QA engineers design test frameworks, write automated test suites, and ensure software meets quality standards before release. The shift toward test automation and DevOps integration has elevated the role from manual testing to engineering-adjacent positions requiring programming skills.",
  },
  {
    slug: 'ai-engineer',
    title: 'AI Engineer',
    category: 'Technology',
    medianSalary: 165000,
    p25Salary: 130000,
    p75Salary: 215000,
    p90Salary: 280000,
    entryLevel: 110000,
    seniorLevel: 240000,
    topStates: ['california', 'washington', 'new-york', 'massachusetts', 'texas'],
    topCities: ['San Francisco', 'Seattle', 'New York City'],
    jobGrowth: 45,
    education: "Master's or PhD in Computer Science, AI, or related field",
    desc: "AI engineers build production systems using large language models, computer vision, and other AI technologies, translating research breakthroughs into deployed products. The ChatGPT boom since late 2022 has created one of the fastest-growing compensation curves in tech history.",
  },
  {
    slug: 'systems-administrator',
    title: 'Systems Administrator',
    category: 'Technology',
    medianSalary: 91000,
    p25Salary: 70000,
    p75Salary: 118000,
    p90Salary: 148000,
    entryLevel: 55000,
    seniorLevel: 130000,
    topStates: ['california', 'texas', 'virginia', 'new-york', 'washington'],
    topCities: ['Washington DC', 'New York City', 'Dallas'],
    jobGrowth: -3,
    education: "Bachelor's in Computer Science or IT; Microsoft, Linux certifications common",
    desc: "Systems administrators manage on-premise and hybrid server environments, handling installation, configuration, and maintenance of operating systems and applications. Cloud migration has shifted many traditional sysadmin tasks to cloud engineers, though organizations with legacy infrastructure continue to hire.",
  },
  {
    slug: 'network-engineer',
    title: 'Network Engineer',
    category: 'Technology',
    medianSalary: 105000,
    p25Salary: 82000,
    p75Salary: 135000,
    p90Salary: 168000,
    entryLevel: 65000,
    seniorLevel: 150000,
    topStates: ['virginia', 'california', 'texas', 'florida', 'new-york'],
    topCities: ['Washington DC', 'Dallas', 'San Francisco'],
    jobGrowth: 4,
    education: "Bachelor's in Computer Science or IT; CCNP, CCNA certifications standard",
    desc: "Network engineers design, implement, and maintain the local and wide-area networks that connect enterprise systems. Federal government contractors in the Washington DC area represent a significant employer segment, with security clearance holders commanding notable salary premiums.",
  },

  // Healthcare
  {
    slug: 'physician',
    title: 'Physician (General)',
    category: 'Healthcare',
    medianSalary: 230000,
    p25Salary: 185000,
    p75Salary: 310000,
    p90Salary: 400000,
    entryLevel: 180000,
    seniorLevel: 350000,
    topStates: ['california', 'new-york', 'texas', 'florida', 'illinois'],
    topCities: ['New York City', 'Los Angeles', 'Chicago'],
    jobGrowth: 3,
    education: 'MD or DO degree plus 3–7 years residency/fellowship',
    desc: "Physicians diagnose and treat illnesses, with compensation varying dramatically by specialty — primary care physicians average around $230,000 while specialists in orthopedics, cardiology, and plastic surgery regularly exceed $500,000. Medical school debt averaging $200,000 remains the primary financial trade-off.",
  },
  {
    slug: 'surgeon',
    title: 'Surgeon',
    category: 'Healthcare',
    medianSalary: 409665,
    p25Salary: 320000,
    p75Salary: 550000,
    p90Salary: 750000,
    entryLevel: 280000,
    seniorLevel: 600000,
    topStates: ['california', 'new-york', 'texas', 'florida', 'illinois'],
    topCities: ['New York City', 'Los Angeles', 'Houston'],
    jobGrowth: 3,
    education: 'MD plus 5–7 year surgical residency, possible fellowship',
    desc: "Surgeons perform operations across specialties including orthopedics, cardiovascular, neurosurgery, and general surgery. Orthopedic surgeons consistently rank as the highest-paid physicians in the US, with median compensation exceeding $600,000 at mature practices.",
  },
  {
    slug: 'dentist',
    title: 'Dentist',
    category: 'Healthcare',
    medianSalary: 175000,
    p25Salary: 130000,
    p75Salary: 245000,
    p90Salary: 350000,
    entryLevel: 110000,
    seniorLevel: 280000,
    topStates: ['california', 'new-york', 'texas', 'florida', 'washington'],
    topCities: ['Los Angeles', 'New York City', 'Seattle'],
    jobGrowth: 4,
    education: 'DDS or DMD degree, 4 years post-undergraduate',
    desc: "Dentists provide preventive care and treat oral diseases, with a growing share of compensation coming from cosmetic procedures like implants, veneers, and clear aligners. Ownership of a private practice dramatically increases earning potential compared to associate positions.",
  },
  {
    slug: 'registered-nurse',
    title: 'Registered Nurse',
    category: 'Healthcare',
    medianSalary: 86070,
    p25Salary: 71000,
    p75Salary: 104000,
    p90Salary: 130000,
    entryLevel: 58000,
    seniorLevel: 115000,
    topStates: ['california', 'hawaii', 'oregon', 'alaska', 'massachusetts'],
    topCities: ['San Francisco', 'Seattle', 'Los Angeles'],
    jobGrowth: 6,
    education: 'BSN (Bachelor of Science in Nursing) increasingly preferred; ADN accepted',
    desc: "Registered nurses provide patient care across hospitals, clinics, and home health settings, with California setting the national salary high — RNs there average over $130,000 versus the $86,000 national median. Critical care, ICU, and travel nursing assignments command the largest premiums.",
  },
  {
    slug: 'nurse-practitioner',
    title: 'Nurse Practitioner',
    category: 'Healthcare',
    medianSalary: 126260,
    p25Salary: 108000,
    p75Salary: 148000,
    p90Salary: 180000,
    entryLevel: 95000,
    seniorLevel: 165000,
    topStates: ['california', 'washington', 'new-york', 'hawaii', 'alaska'],
    topCities: ['San Francisco', 'Seattle', 'New York City'],
    jobGrowth: 38,
    education: "Master's of Science in Nursing (MSN); Doctor of Nursing Practice (DNP) growing",
    desc: "Nurse practitioners hold prescriptive authority and manage patients independently in the 27 states with full practice authority, effectively functioning as primary care providers. The BLS projects 38% job growth through 2032 as NPs fill physician shortages across rural and underserved areas.",
  },
  {
    slug: 'physician-assistant',
    title: 'Physician Assistant',
    category: 'Healthcare',
    medianSalary: 130020,
    p25Salary: 108000,
    p75Salary: 155000,
    p90Salary: 185000,
    entryLevel: 95000,
    seniorLevel: 168000,
    topStates: ['california', 'washington', 'new-york', 'hawaii', 'connecticut'],
    topCities: ['San Francisco', 'New York City', 'Seattle'],
    jobGrowth: 28,
    education: "Master's degree from ARC-PA accredited PA program",
    desc: "Physician assistants diagnose illnesses and develop treatment plans under physician supervision, with surgical and emergency medicine specialties commanding the highest compensation. PA programs take roughly 27 months and represent a faster path to high healthcare salaries than medical school.",
  },
  {
    slug: 'pharmacist',
    title: 'Pharmacist',
    category: 'Healthcare',
    medianSalary: 134900,
    p25Salary: 115000,
    p75Salary: 158000,
    p90Salary: 188000,
    entryLevel: 105000,
    seniorLevel: 170000,
    topStates: ['california', 'alaska', 'maine', 'connecticut', 'hawaii'],
    topCities: ['San Francisco', 'Los Angeles', 'New York City'],
    jobGrowth: -2,
    education: 'PharmD (Doctor of Pharmacy), 4 years post-undergraduate',
    desc: "Pharmacists dispense medications, counsel patients on drug interactions, and increasingly provide clinical pharmacy services in hospital and ambulatory care settings. The retail pharmacy sector faces automation pressure from mail-order and robotic dispensing, while clinical hospital roles remain stable.",
  },
  {
    slug: 'physical-therapist',
    title: 'Physical Therapist',
    category: 'Healthcare',
    medianSalary: 99710,
    p25Salary: 82000,
    p75Salary: 120000,
    p90Salary: 145000,
    entryLevel: 68000,
    seniorLevel: 130000,
    topStates: ['california', 'new-jersey', 'nevada', 'connecticut', 'alaska'],
    topCities: ['San Francisco', 'Los Angeles', 'New York City'],
    jobGrowth: 15,
    education: 'DPT (Doctor of Physical Therapy), entry-level doctoral degree required since 2016',
    desc: "Physical therapists restore mobility and manage pain for patients recovering from injuries, surgeries, and chronic conditions. The aging baby boomer population drives steady demand, and travel PT contracts in shortage areas pay a substantial premium over permanent positions.",
  },
  {
    slug: 'anesthesiologist',
    title: 'Anesthesiologist',
    category: 'Healthcare',
    medianSalary: 331190,
    p25Salary: 280000,
    p75Salary: 420000,
    p90Salary: 550000,
    entryLevel: 250000,
    seniorLevel: 480000,
    topStates: ['wyoming', 'kentucky', 'alabama', 'nebraska', 'indiana'],
    topCities: ['Chicago', 'Houston', 'Dallas'],
    jobGrowth: 5,
    education: 'MD/DO plus 4-year anesthesiology residency and optional fellowship',
    desc: "Anesthesiologists administer anesthesia for surgical and medical procedures, monitoring patient vitals throughout. Despite the highest median salary among all BLS occupation categories alongside surgeons, anesthesiology faces growing competition from Certified Registered Nurse Anesthetists who can practice independently in 29 states.",
  },
  {
    slug: 'psychiatrist',
    title: 'Psychiatrist',
    category: 'Healthcare',
    medianSalary: 247350,
    p25Salary: 195000,
    p75Salary: 330000,
    p90Salary: 430000,
    entryLevel: 175000,
    seniorLevel: 370000,
    topStates: ['california', 'new-york', 'massachusetts', 'connecticut', 'minnesota'],
    topCities: ['New York City', 'Los Angeles', 'San Francisco'],
    jobGrowth: 12,
    education: 'MD/DO plus 4-year psychiatry residency; fellowship optional',
    desc: "Psychiatrists diagnose and treat mental health disorders using medication management and psychotherapy. The national shortage of psychiatrists — the BLS reports fewer than 32,000 in the workforce — keeps salaries elevated, and telepsychiatry has dramatically expanded geographic reach.",
  },
  {
    slug: 'psychologist',
    title: 'Psychologist',
    category: 'Healthcare',
    medianSalary: 92000,
    p25Salary: 72000,
    p75Salary: 126000,
    p90Salary: 165000,
    entryLevel: 60000,
    seniorLevel: 140000,
    topStates: ['california', 'new-jersey', 'oregon', 'new-york', 'connecticut'],
    topCities: ['New York City', 'Los Angeles', 'San Francisco'],
    jobGrowth: 6,
    education: 'PhD or PsyD in Psychology; supervised hours required for licensure',
    desc: "Psychologists provide assessment, therapy, and consultation across clinical, school, and industrial-organizational settings. Clinical and counseling psychologists earning potential is capped compared to psychiatrists since most states restrict prescriptive authority, though industrial-organizational psychologists in corporate settings can earn significantly more.",
  },
  {
    slug: 'radiologist',
    title: 'Radiologist',
    category: 'Healthcare',
    medianSalary: 413000,
    p25Salary: 320000,
    p75Salary: 520000,
    p90Salary: 660000,
    entryLevel: 280000,
    seniorLevel: 580000,
    topStates: ['california', 'new-york', 'texas', 'florida', 'ohio'],
    topCities: ['New York City', 'Chicago', 'Houston'],
    jobGrowth: 6,
    education: 'MD/DO plus 5-year radiology residency and optional subspecialty fellowship',
    desc: "Radiologists interpret medical images from X-rays, CT scans, MRIs, and ultrasounds to diagnose diseases. Teleradiology has enabled night coverage from different time zones while pushing more competitive pricing into the market, though subspecialists in interventional radiology remain highly compensated.",
  },
  {
    slug: 'dental-hygienist',
    title: 'Dental Hygienist',
    category: 'Healthcare',
    medianSalary: 84470,
    p25Salary: 68000,
    p75Salary: 103000,
    p90Salary: 126000,
    entryLevel: 55000,
    seniorLevel: 112000,
    topStates: ['alaska', 'washington', 'california', 'nevada', 'new-jersey'],
    topCities: ['Seattle', 'San Francisco', 'Los Angeles'],
    jobGrowth: 9,
    education: "Associate's degree in Dental Hygiene; licensure required in all states",
    desc: "Dental hygienists clean teeth, examine patients for oral diseases, and provide preventive care services in dental offices. Alaska and Washington consistently top the state compensation rankings, with the national median understating actual earnings in coastal markets.",
  },
  {
    slug: 'paramedic',
    title: 'Paramedic',
    category: 'Healthcare',
    medianSalary: 59860,
    p25Salary: 46000,
    p75Salary: 76000,
    p90Salary: 95000,
    entryLevel: 38000,
    seniorLevel: 82000,
    topStates: ['washington', 'hawaii', 'new-jersey', 'california', 'massachusetts'],
    topCities: ['Seattle', 'San Francisco', 'New York City'],
    jobGrowth: 9,
    education: 'Paramedic certification; EMT-B license as prerequisite; 1,200+ clinical hours',
    desc: "Paramedics provide advanced emergency medical care in the field, administering medications, interpreting ECGs, and performing advanced airway management. Fire department-based paramedics typically earn significantly more than private ambulance service counterparts.",
  },
  {
    slug: 'veterinarian',
    title: 'Veterinarian',
    category: 'Healthcare',
    medianSalary: 125510,
    p25Salary: 98000,
    p75Salary: 165000,
    p90Salary: 215000,
    entryLevel: 85000,
    seniorLevel: 185000,
    topStates: ['california', 'new-jersey', 'connecticut', 'new-york', 'hawaii'],
    topCities: ['New York City', 'Los Angeles', 'San Francisco'],
    jobGrowth: 19,
    education: 'DVM or VMD degree, 4 years post-undergraduate',
    desc: "Veterinarians diagnose and treat animal diseases across companion animal practice, food animal medicine, research, and public health. The pandemic-era pet adoption surge has driven a veterinarian shortage that has pushed practice salaries well above the BLS median in high-demand markets.",
  },
  {
    slug: 'occupational-therapist',
    title: 'Occupational Therapist',
    category: 'Healthcare',
    medianSalary: 96370,
    p25Salary: 80000,
    p75Salary: 116000,
    p90Salary: 138000,
    entryLevel: 65000,
    seniorLevel: 125000,
    topStates: ['california', 'nevada', 'new-jersey', 'arizona', 'virginia'],
    topCities: ['San Francisco', 'Los Angeles', 'New York City'],
    jobGrowth: 12,
    education: "Master's degree in Occupational Therapy; NBCOT exam required for licensure",
    desc: "Occupational therapists help patients regain functional independence after illness, injury, or disability, working in hospitals, schools, and home health settings. Pediatric OT and hand therapy specializations represent the highest-earning practice areas.",
  },
  {
    slug: 'healthcare-administrator',
    title: 'Healthcare Administrator',
    category: 'Healthcare',
    medianSalary: 119840,
    p25Salary: 90000,
    p75Salary: 162000,
    p90Salary: 220000,
    entryLevel: 70000,
    seniorLevel: 185000,
    topStates: ['california', 'new-york', 'new-jersey', 'connecticut', 'massachusetts'],
    topCities: ['New York City', 'Los Angeles', 'Chicago'],
    jobGrowth: 28,
    education: "Master's in Health Administration (MHA) or MBA with healthcare focus",
    desc: "Healthcare administrators manage hospitals, clinics, and medical practices — overseeing finances, staffing, regulatory compliance, and strategic planning. Hospital CEOs at large academic medical centers routinely earn over $1 million in total compensation.",
  },

  // Finance
  {
    slug: 'financial-advisor',
    title: 'Financial Advisor',
    category: 'Finance',
    medianSalary: 99580,
    p25Salary: 65000,
    p75Salary: 165000,
    p90Salary: 280000,
    entryLevel: 50000,
    seniorLevel: 250000,
    topStates: ['new-york', 'connecticut', 'massachusetts', 'california', 'new-jersey'],
    topCities: ['New York City', 'Boston', 'San Francisco'],
    jobGrowth: 13,
    education: "Bachelor's in Finance or Business; CFP certification highly valued; Series 7 and 65/66 licenses required",
    desc: "Financial advisors provide investment guidance, retirement planning, and wealth management services to individuals and families. Commission and AUM-based compensation means top performers at wirehouse and independent broker-dealer firms regularly earn seven figures.",
  },
  {
    slug: 'investment-banker',
    title: 'Investment Banker',
    category: 'Finance',
    medianSalary: 175000,
    p25Salary: 130000,
    p75Salary: 280000,
    p90Salary: 500000,
    entryLevel: 110000,
    seniorLevel: 400000,
    topStates: ['new-york', 'california', 'illinois', 'massachusetts', 'connecticut'],
    topCities: ['New York City', 'San Francisco', 'Chicago'],
    jobGrowth: 10,
    education: "Bachelor's from target university; MBA from top business school for associate-level entry",
    desc: "Investment bankers advise corporations and governments on mergers, acquisitions, and capital raises, working notoriously long hours in exchange for performance bonuses that can dwarf base salaries. A Goldman Sachs or JPMorgan analyst earning $110,000 base may take home $150,000–$200,000 after first-year bonuses.",
  },
  {
    slug: 'accountant',
    title: 'Accountant',
    category: 'Finance',
    medianSalary: 79880,
    p25Salary: 61000,
    p75Salary: 106000,
    p90Salary: 140000,
    entryLevel: 50000,
    seniorLevel: 120000,
    topStates: ['new-york', 'new-jersey', 'california', 'connecticut', 'district-of-columbia'],
    topCities: ['New York City', 'Washington DC', 'San Francisco'],
    jobGrowth: 4,
    education: "Bachelor's in Accounting; 150 credit hours required for CPA licensure",
    desc: "Accountants prepare financial statements, manage tax compliance, and provide audit services across public accounting firms, corporations, and government agencies. Big Four firm partners earn $500,000 or more, while entry-level staff at regional firms start in the $50,000–$65,000 range.",
  },
  {
    slug: 'cpa',
    title: 'Certified Public Accountant (CPA)',
    category: 'Finance',
    medianSalary: 95000,
    p25Salary: 72000,
    p75Salary: 130000,
    p90Salary: 175000,
    entryLevel: 58000,
    seniorLevel: 145000,
    topStates: ['new-york', 'california', 'connecticut', 'new-jersey', 'massachusetts'],
    topCities: ['New York City', 'San Francisco', 'Washington DC'],
    jobGrowth: 4,
    education: "Bachelor's in Accounting plus 150 credit hours; four CPA exam sections",
    desc: "CPAs hold the gold-standard accounting credential, earning a consistent 10–15% salary premium over non-certified accountants. Tax CPAs at Big Four firms and forensic accountants at consulting practices represent two of the highest-earning specializations within the credential.",
  },
  {
    slug: 'financial-analyst',
    title: 'Financial Analyst',
    category: 'Finance',
    medianSalary: 99890,
    p25Salary: 74000,
    p75Salary: 135000,
    p90Salary: 180000,
    entryLevel: 60000,
    seniorLevel: 155000,
    topStates: ['new-york', 'connecticut', 'california', 'massachusetts', 'new-jersey'],
    topCities: ['New York City', 'Boston', 'San Francisco'],
    jobGrowth: 8,
    education: "Bachelor's in Finance, Economics, or Accounting; CFA charter highly valued",
    desc: "Financial analysts evaluate investment opportunities, build financial models, and produce research that guides capital allocation decisions at banks, asset managers, and corporations. Buy-side analysts at hedge funds and private equity firms represent the highest-earning segment of the profession.",
  },
  {
    slug: 'actuary',
    title: 'Actuary',
    category: 'Finance',
    medianSalary: 120000,
    p25Salary: 92000,
    p75Salary: 158000,
    p90Salary: 210000,
    entryLevel: 70000,
    seniorLevel: 175000,
    topStates: ['connecticut', 'new-york', 'illinois', 'minnesota', 'new-jersey'],
    topCities: ['Hartford', 'New York City', 'Chicago'],
    jobGrowth: 23,
    education: "Bachelor's in Mathematics, Statistics, or Actuarial Science; series of professional exams (10+ years to fellowship)",
    desc: "Actuaries use probability theory and statistical models to assess financial risk for insurance companies, pension funds, and government programs. Each exam passed during the credentialing process typically triggers a salary increase, with fully credentialed fellows (FCAS or FSA) among the most reliably compensated professionals in finance.",
  },
  {
    slug: 'cfo',
    title: 'Chief Financial Officer (CFO)',
    category: 'Finance',
    medianSalary: 210000,
    p25Salary: 155000,
    p75Salary: 340000,
    p90Salary: 550000,
    entryLevel: 140000,
    seniorLevel: 450000,
    topStates: ['new-york', 'california', 'connecticut', 'illinois', 'texas'],
    topCities: ['New York City', 'San Francisco', 'Chicago'],
    jobGrowth: 15,
    education: "Bachelor's in Finance or Accounting; MBA common; CPA valued",
    desc: "CFOs oversee financial planning, risk management, investor relations, and corporate strategy, reporting directly to the CEO. At S&P 500 companies, median CFO total compensation exceeds $5 million annually when stock awards and performance bonuses are included.",
  },
  {
    slug: 'loan-officer',
    title: 'Loan Officer',
    category: 'Finance',
    medianSalary: 69990,
    p25Salary: 48000,
    p75Salary: 106000,
    p90Salary: 155000,
    entryLevel: 40000,
    seniorLevel: 130000,
    topStates: ['california', 'new-york', 'texas', 'florida', 'washington'],
    topCities: ['Los Angeles', 'New York City', 'Dallas'],
    jobGrowth: 3,
    education: "Bachelor's degree preferred; Mortgage Loan Originator (MLO) license required for residential mortgage lending",
    desc: "Loan officers evaluate and approve loan applications for individuals and businesses, with commission-heavy compensation in mortgage lending creating wide income variation based on interest rate cycles. The 2022–2024 rate environment dramatically reduced mortgage origination volume and squeezed total compensation.",
  },
  {
    slug: 'portfolio-manager',
    title: 'Portfolio Manager',
    category: 'Finance',
    medianSalary: 175000,
    p25Salary: 130000,
    p75Salary: 280000,
    p90Salary: 500000,
    entryLevel: 110000,
    seniorLevel: 400000,
    topStates: ['new-york', 'connecticut', 'california', 'massachusetts', 'illinois'],
    topCities: ['New York City', 'Greenwich', 'Boston'],
    jobGrowth: 8,
    education: "Bachelor's in Finance, Economics, or Mathematics; CFA charter strongly preferred; MBA common",
    desc: "Portfolio managers allocate capital across asset classes to maximize risk-adjusted returns for mutual funds, hedge funds, pension funds, and endowments. Hedge fund PM compensation is largely performance-driven, with successful managers at top funds earning hundreds of millions in carried interest.",
  },
  {
    slug: 'economist',
    title: 'Economist',
    category: 'Finance',
    medianSalary: 115730,
    p25Salary: 85000,
    p75Salary: 162000,
    p90Salary: 220000,
    entryLevel: 65000,
    seniorLevel: 180000,
    topStates: ['district-of-columbia', 'new-york', 'california', 'massachusetts', 'virginia'],
    topCities: ['Washington DC', 'New York City', 'San Francisco'],
    jobGrowth: 6,
    education: "Master's or PhD in Economics for most positions; Bachelor's for entry-level government roles",
    desc: "Economists analyze data to understand market behavior, forecast economic trends, and advise policy makers and businesses. Federal government agencies in Washington DC — the Federal Reserve, Bureau of Labor Statistics, and Congressional Budget Office — represent a major employer segment.",
  },

  // Legal
  {
    slug: 'lawyer',
    title: 'Lawyer',
    category: 'Legal',
    medianSalary: 145760,
    p25Salary: 88000,
    p75Salary: 228000,
    p90Salary: 400000,
    entryLevel: 75000,
    seniorLevel: 300000,
    topStates: ['california', 'new-york', 'illinois', 'massachusetts', 'connecticut'],
    topCities: ['New York City', 'San Francisco', 'Washington DC'],
    jobGrowth: 8,
    education: 'JD degree plus bar examination; 3 years post-undergraduate law school',
    desc: "Lawyers advise clients and represent them in legal proceedings across practice areas including corporate law, litigation, real estate, and intellectual property. Big Law associates at top firms in New York earn a starting salary of $225,000 — a figure that obscures the wide gap between elite firm and public sector pay.",
  },
  {
    slug: 'paralegal',
    title: 'Paralegal',
    category: 'Legal',
    medianSalary: 63380,
    p25Salary: 48000,
    p75Salary: 83000,
    p90Salary: 108000,
    entryLevel: 38000,
    seniorLevel: 92000,
    topStates: ['california', 'district-of-columbia', 'connecticut', 'massachusetts', 'new-york'],
    topCities: ['Washington DC', 'New York City', 'San Francisco'],
    jobGrowth: 4,
    education: "Associate's or Bachelor's degree in Paralegal Studies; ABA-approved programs preferred",
    desc: "Paralegals assist attorneys with legal research, document review, case preparation, and client communication, with large-firm corporate paralegals in major markets earning significantly above the national median. Specialization in areas like e-discovery, IP, or securities law carries distinct salary premiums.",
  },
  {
    slug: 'corporate-attorney',
    title: 'Corporate Attorney',
    category: 'Legal',
    medianSalary: 195000,
    p25Salary: 140000,
    p75Salary: 310000,
    p90Salary: 500000,
    entryLevel: 120000,
    seniorLevel: 400000,
    topStates: ['new-york', 'california', 'illinois', 'massachusetts', 'connecticut'],
    topCities: ['New York City', 'San Francisco', 'Chicago'],
    jobGrowth: 8,
    education: 'JD from top law school; Law Review, moot court participation valued',
    desc: "Corporate attorneys advise companies on M&A transactions, securities offerings, board governance, and commercial contracts. Lockstep pay at elite firms means associates follow predictable salary tracks — a 4th-year associate at a top-50 firm earns $280,000 in base salary alone.",
  },
  {
    slug: 'patent-attorney',
    title: 'Patent Attorney',
    category: 'Legal',
    medianSalary: 195000,
    p25Salary: 148000,
    p75Salary: 260000,
    p90Salary: 380000,
    entryLevel: 125000,
    seniorLevel: 300000,
    topStates: ['california', 'new-york', 'texas', 'massachusetts', 'new-jersey'],
    topCities: ['San Francisco', 'New York City', 'Boston'],
    jobGrowth: 7,
    education: 'JD plus STEM undergraduate degree; USPTO patent bar exam required',
    desc: "Patent attorneys prosecute and defend patents, requiring the rare combination of legal training and technical engineering or science expertise. The dual qualification commands one of the largest salary premiums within the legal profession, particularly in biotechnology and semiconductor litigation.",
  },
  {
    slug: 'immigration-attorney',
    title: 'Immigration Attorney',
    category: 'Legal',
    medianSalary: 92000,
    p25Salary: 66000,
    p75Salary: 135000,
    p90Salary: 195000,
    entryLevel: 52000,
    seniorLevel: 160000,
    topStates: ['california', 'new-york', 'texas', 'florida', 'new-jersey'],
    topCities: ['New York City', 'Los Angeles', 'Miami'],
    jobGrowth: 10,
    education: 'JD degree and bar admission; immigration law specialization coursework valuable',
    desc: "Immigration attorneys handle visa applications, green cards, deportation defense, and business immigration matters. The corporate immigration sector — helping companies sponsor skilled worker visas — commands significantly higher fees and salaries than individual client representation.",
  },

  // Education
  {
    slug: 'teacher',
    title: 'Elementary School Teacher',
    category: 'Education',
    medianSalary: 63680,
    p25Salary: 50000,
    p75Salary: 84000,
    p90Salary: 108000,
    entryLevel: 40000,
    seniorLevel: 90000,
    topStates: ['california', 'new-york', 'alaska', 'connecticut', 'massachusetts'],
    topCities: ['San Francisco', 'New York City', 'Seattle'],
    jobGrowth: 2,
    education: "Bachelor's in Education; state teaching license required; subject endorsements add value",
    desc: "Elementary school teachers educate students in grades K–6 in core subjects, with California paying a median of $95,000 versus Mississippi's $46,000 — the widest state compensation gap of any major profession in the US. Summers off partially offset lower pay, though most teachers work additional hours on curriculum planning.",
  },
  {
    slug: 'high-school-teacher',
    title: 'High School Teacher',
    category: 'Education',
    medianSalary: 66520,
    p25Salary: 52000,
    p75Salary: 90000,
    p90Salary: 115000,
    entryLevel: 42000,
    seniorLevel: 95000,
    topStates: ['california', 'new-york', 'alaska', 'connecticut', 'massachusetts'],
    topCities: ['San Francisco', 'New York City', 'Boston'],
    jobGrowth: 1,
    education: "Bachelor's in Education or subject area; state license required; master's degree increases pay in many districts",
    desc: "High school teachers instruct students in specialized subjects like mathematics, science, English, or history, with STEM subject teachers facing significant competition from the private sector for their skills. New York City teachers earn up to $128,000 after 22 years of experience with a master's degree plus 30 credits.",
  },
  {
    slug: 'college-professor',
    title: 'College Professor',
    category: 'Education',
    medianSalary: 89420,
    p25Salary: 63000,
    p75Salary: 134000,
    p90Salary: 195000,
    entryLevel: 52000,
    seniorLevel: 160000,
    topStates: ['california', 'new-york', 'connecticut', 'new-jersey', 'massachusetts'],
    topCities: ['New York City', 'Boston', 'San Francisco'],
    jobGrowth: 8,
    education: 'PhD in subject discipline; postdoctoral research common before tenure-track position',
    desc: "College professors teach courses, conduct research, and publish academic work, with tenure-track positions at research universities commanding a significant premium over adjunct and lecturer roles. Business, law, and medical school faculty consistently earn the highest salaries in academia.",
  },
  {
    slug: 'school-principal',
    title: 'School Principal',
    category: 'Education',
    medianSalary: 103460,
    p25Salary: 83000,
    p75Salary: 128000,
    p90Salary: 158000,
    entryLevel: 72000,
    seniorLevel: 140000,
    topStates: ['california', 'new-york', 'connecticut', 'alaska', 'new-jersey'],
    topCities: ['New York City', 'San Francisco', 'Los Angeles'],
    jobGrowth: 1,
    education: "Master's in Education Administration; administrative license required in all states",
    desc: "School principals manage day-to-day operations, staff, curriculum, and budgets for elementary, middle, or high schools. Large urban district principals in high-cost states earn over $180,000, while rural district principals may earn considerably less despite similar administrative responsibilities.",
  },
  {
    slug: 'school-counselor',
    title: 'School Counselor',
    category: 'Education',
    medianSalary: 62000,
    p25Salary: 50000,
    p75Salary: 80000,
    p90Salary: 102000,
    entryLevel: 40000,
    seniorLevel: 88000,
    topStates: ['california', 'new-york', 'connecticut', 'new-jersey', 'maryland'],
    topCities: ['New York City', 'San Francisco', 'Washington DC'],
    jobGrowth: 7,
    education: "Master's in School Counseling; state licensure required",
    desc: "School counselors support students' academic development, social-emotional wellbeing, and post-secondary planning across K–12 schools. The ASCA recommends a student-to-counselor ratio of 250:1, though actual ratios in many states exceed 400:1, driving sustained hiring demand.",
  },

  // Engineering
  {
    slug: 'civil-engineer',
    title: 'Civil Engineer',
    category: 'Engineering',
    medianSalary: 95890,
    p25Salary: 74000,
    p75Salary: 124000,
    p90Salary: 158000,
    entryLevel: 60000,
    seniorLevel: 140000,
    topStates: ['california', 'texas', 'new-york', 'nevada', 'washington'],
    topCities: ['San Francisco', 'New York City', 'Seattle'],
    jobGrowth: 5,
    education: "Bachelor's in Civil Engineering; PE license required for public projects",
    desc: "Civil engineers design infrastructure including roads, bridges, water systems, and buildings, with the $1.2 trillion Bipartisan Infrastructure Law sustaining elevated demand for the decade. California and Texas lead employment given their ongoing mega-project pipelines.",
  },
  {
    slug: 'mechanical-engineer',
    title: 'Mechanical Engineer',
    category: 'Engineering',
    medianSalary: 99510,
    p25Salary: 78000,
    p75Salary: 130000,
    p90Salary: 162000,
    entryLevel: 62000,
    seniorLevel: 145000,
    topStates: ['california', 'texas', 'michigan', 'washington', 'ohio'],
    topCities: ['Detroit', 'Houston', 'Los Angeles'],
    jobGrowth: 10,
    education: "Bachelor's in Mechanical Engineering; PE license for certain public roles",
    desc: "Mechanical engineers design, analyze, and manufacture machines, engines, and mechanical systems across aerospace, automotive, energy, and consumer products industries. The automotive electrification transition has created significant new demand in battery thermal management and electric motor design.",
  },
  {
    slug: 'electrical-engineer',
    title: 'Electrical Engineer',
    category: 'Engineering',
    medianSalary: 107890,
    p25Salary: 84000,
    p75Salary: 140000,
    p90Salary: 175000,
    entryLevel: 66000,
    seniorLevel: 155000,
    topStates: ['california', 'texas', 'washington', 'new-york', 'michigan'],
    topCities: ['San Jose', 'Seattle', 'Austin'],
    jobGrowth: 11,
    education: "Bachelor's in Electrical Engineering; PE license optional for most private roles",
    desc: "Electrical engineers design circuits, power systems, and electronics for applications ranging from consumer devices to utility-scale solar installations. Silicon Valley semiconductor companies pay substantially above the BLS median for specialized roles in chip design and power electronics.",
  },
  {
    slug: 'aerospace-engineer',
    title: 'Aerospace Engineer',
    category: 'Engineering',
    medianSalary: 126880,
    p25Salary: 99000,
    p75Salary: 162000,
    p90Salary: 200000,
    entryLevel: 75000,
    seniorLevel: 178000,
    topStates: ['california', 'washington', 'texas', 'florida', 'alabama'],
    topCities: ['Los Angeles', 'Seattle', 'Houston'],
    jobGrowth: 6,
    education: "Bachelor's in Aerospace Engineering; security clearance valuable for defense roles",
    desc: "Aerospace engineers design aircraft, spacecraft, missiles, and satellites, with SpaceX, Boeing, Northrop Grumman, and Lockheed Martin representing the largest private employers. Defense contractors with security clearance requirements often pay a 10–20% premium over commercial aerospace roles.",
  },
  {
    slug: 'petroleum-engineer',
    title: 'Petroleum Engineer',
    category: 'Engineering',
    medianSalary: 145720,
    p25Salary: 115000,
    p75Salary: 190000,
    p90Salary: 240000,
    entryLevel: 90000,
    seniorLevel: 210000,
    topStates: ['texas', 'oklahoma', 'wyoming', 'colorado', 'north-dakota'],
    topCities: ['Houston', 'Midland', 'Oklahoma City'],
    jobGrowth: -2,
    education: "Bachelor's in Petroleum Engineering; field experience in Permian Basin, Gulf Coast valued",
    desc: "Petroleum engineers develop methods to extract oil and gas efficiently, with Texas and the Permian Basin dominating employment. The highest-paid engineering specialty by BLS data, though oil price volatility creates boom-bust hiring cycles that have produced significant layoffs in downcycles.",
  },
  {
    slug: 'chemical-engineer',
    title: 'Chemical Engineer',
    category: 'Engineering',
    medianSalary: 116230,
    p25Salary: 91000,
    p75Salary: 151000,
    p90Salary: 195000,
    entryLevel: 72000,
    seniorLevel: 165000,
    topStates: ['texas', 'california', 'new-jersey', 'louisiana', 'michigan'],
    topCities: ['Houston', 'Philadelphia', 'San Francisco'],
    jobGrowth: 8,
    education: "Bachelor's in Chemical Engineering",
    desc: "Chemical engineers apply principles of chemistry, biology, and physics to transform raw materials into useful products including fuels, plastics, pharmaceuticals, and food. The petrochemical industry in Texas and Louisiana represents the largest employment sector.",
  },
  {
    slug: 'biomedical-engineer',
    title: 'Biomedical Engineer',
    category: 'Engineering',
    medianSalary: 99550,
    p25Salary: 76000,
    p75Salary: 130000,
    p90Salary: 162000,
    entryLevel: 62000,
    seniorLevel: 145000,
    topStates: ['california', 'massachusetts', 'minnesota', 'new-york', 'new-jersey'],
    topCities: ['Boston', 'San Francisco', 'Minneapolis'],
    jobGrowth: 5,
    education: "Bachelor's in Biomedical Engineering; advanced degree for R&D roles",
    desc: "Biomedical engineers design medical devices, prosthetics, diagnostic equipment, and drug delivery systems. Boston and the Twin Cities have emerged as major hubs given the concentration of medical device companies like Medtronic, Boston Scientific, and Abbott.",
  },

  // Business/Management
  {
    slug: 'ceo',
    title: 'Chief Executive Officer (CEO)',
    category: 'Business',
    medianSalary: 258560,
    p25Salary: 150000,
    p75Salary: 500000,
    p90Salary: 1500000,
    entryLevel: 120000,
    seniorLevel: 800000,
    topStates: ['new-york', 'california', 'texas', 'illinois', 'florida'],
    topCities: ['New York City', 'San Francisco', 'Chicago'],
    jobGrowth: 3,
    education: "Bachelor's required; MBA from top program common; industry experience paramount",
    desc: "CEOs set organizational strategy and are accountable for financial performance, reporting to boards of directors. At S&P 500 companies, median CEO total compensation exceeded $15 million in 2024, largely through stock awards — a figure that dwarfs what most small and mid-size company CEOs earn.",
  },
  {
    slug: 'marketing-manager',
    title: 'Marketing Manager',
    category: 'Business',
    medianSalary: 161580,
    p25Salary: 118000,
    p75Salary: 214000,
    p90Salary: 285000,
    entryLevel: 80000,
    seniorLevel: 235000,
    topStates: ['new-york', 'california', 'illinois', 'connecticut', 'washington'],
    topCities: ['New York City', 'San Francisco', 'Chicago'],
    jobGrowth: 8,
    education: "Bachelor's in Marketing or Business; MBA common at director level",
    desc: "Marketing managers develop and execute campaigns across digital, brand, and product marketing, with technology sector marketing managers earning the highest median compensation in the profession. Growth marketing and performance marketing specializations command notable premiums over traditional brand roles.",
  },
  {
    slug: 'project-manager',
    title: 'Project Manager',
    category: 'Business',
    medianSalary: 104000,
    p25Salary: 80000,
    p75Salary: 134000,
    p90Salary: 168000,
    entryLevel: 62000,
    seniorLevel: 148000,
    topStates: ['california', 'virginia', 'new-york', 'texas', 'washington'],
    topCities: ['Washington DC', 'New York City', 'San Francisco'],
    jobGrowth: 7,
    education: "Bachelor's in Business or relevant field; PMP certification widely valued",
    desc: "Project managers plan, execute, and close projects on time and within budget across industries from construction to IT. The Project Management Professional (PMP) certification from PMI adds a consistent 20% salary premium, with technology sector PMs earning most.",
  },
  {
    slug: 'hr-manager',
    title: 'HR Manager',
    category: 'Business',
    medianSalary: 136350,
    p25Salary: 101000,
    p75Salary: 178000,
    p90Salary: 230000,
    entryLevel: 72000,
    seniorLevel: 195000,
    topStates: ['new-york', 'california', 'new-jersey', 'connecticut', 'washington'],
    topCities: ['New York City', 'San Francisco', 'Seattle'],
    jobGrowth: 5,
    education: "Bachelor's in HR or Business; SHRM-CP or SHRM-SCP certification valued",
    desc: "HR managers oversee talent acquisition, employee relations, benefits administration, and compliance across organizations. Chief People Officer and VP of People roles at technology companies command compensation packages well above the BLS median due to equity compensation.",
  },
  {
    slug: 'management-consultant',
    title: 'Management Consultant',
    category: 'Business',
    medianSalary: 107200,
    p25Salary: 80000,
    p75Salary: 160000,
    p90Salary: 265000,
    entryLevel: 85000,
    seniorLevel: 220000,
    topStates: ['new-york', 'illinois', 'california', 'massachusetts', 'virginia'],
    topCities: ['New York City', 'Chicago', 'Washington DC'],
    jobGrowth: 11,
    education: "Bachelor's from target school; MBA from M7 program for post-MBA associate roles",
    desc: "Management consultants advise organizations on strategy, operations, and organizational change at firms like McKinsey, Bain, BCG, Deloitte, and Accenture. MBB (McKinsey, Bain, BCG) post-MBA associates start at $190,000 base plus a $35,000 signing bonus and performance bonuses.",
  },
  {
    slug: 'operations-manager',
    title: 'Operations Manager',
    category: 'Business',
    medianSalary: 107200,
    p25Salary: 78000,
    p75Salary: 148000,
    p90Salary: 195000,
    entryLevel: 58000,
    seniorLevel: 165000,
    topStates: ['california', 'new-york', 'texas', 'washington', 'virginia'],
    topCities: ['New York City', 'Los Angeles', 'Chicago'],
    jobGrowth: 6,
    education: "Bachelor's in Business Administration or Operations Management",
    desc: "Operations managers optimize business processes, supply chains, and workforce management to maximize efficiency and reduce costs. The role spans industries from manufacturing to logistics to healthcare, with technology operations and supply chain management commanding the highest salaries.",
  },
  {
    slug: 'business-analyst',
    title: 'Business Analyst',
    category: 'Business',
    medianSalary: 99880,
    p25Salary: 75000,
    p75Salary: 131000,
    p90Salary: 168000,
    entryLevel: 58000,
    seniorLevel: 145000,
    topStates: ['california', 'new-york', 'virginia', 'washington', 'illinois'],
    topCities: ['Washington DC', 'New York City', 'San Francisco'],
    jobGrowth: 11,
    education: "Bachelor's in Business, IT, or Finance; PMP or CBAP certification helpful",
    desc: "Business analysts bridge the gap between business stakeholders and technical teams, translating requirements into functional specifications and process improvements. Specialization in financial services, healthcare systems, or enterprise ERP implementations commands the largest premiums.",
  },
  {
    slug: 'sales-manager',
    title: 'Sales Manager',
    category: 'Business',
    medianSalary: 135160,
    p25Salary: 90000,
    p75Salary: 208000,
    p90Salary: 360000,
    entryLevel: 65000,
    seniorLevel: 250000,
    topStates: ['new-york', 'california', 'connecticut', 'new-jersey', 'illinois'],
    topCities: ['New York City', 'San Francisco', 'Chicago'],
    jobGrowth: 4,
    education: "Bachelor's in Business or related field; track record of quota attainment paramount",
    desc: "Sales managers lead revenue teams, set quotas, coach reps, and forecast pipeline, with software and pharmaceutical sales management representing the highest-earning segments. On-target earnings at technology companies regularly exceed $300,000 for regional and enterprise sales management roles.",
  },

  // Trades
  {
    slug: 'electrician',
    title: 'Electrician',
    category: 'Trades',
    medianSalary: 66260,
    p25Salary: 51000,
    p75Salary: 90000,
    p90Salary: 115000,
    entryLevel: 38000,
    seniorLevel: 100000,
    topStates: ['alaska', 'illinois', 'new-york', 'hawaii', 'california'],
    topCities: ['New York City', 'Chicago', 'Los Angeles'],
    jobGrowth: 11,
    education: '4–5 year apprenticeship program; state electrician license required',
    desc: "Electricians install and maintain electrical systems in homes, businesses, and industrial facilities, with the renewable energy buildout — solar, wind, and EV charging infrastructure — creating sustained new demand. Union electricians in New York City and Chicago earn the highest total compensation in the profession.",
  },
  {
    slug: 'plumber',
    title: 'Plumber',
    category: 'Trades',
    medianSalary: 64480,
    p25Salary: 48000,
    p75Salary: 88000,
    p90Salary: 112000,
    entryLevel: 36000,
    seniorLevel: 98000,
    topStates: ['illinois', 'new-york', 'alaska', 'hawaii', 'new-jersey'],
    topCities: ['New York City', 'Chicago', 'Los Angeles'],
    jobGrowth: 6,
    education: '4–5 year apprenticeship; journeyman and master plumber licenses required',
    desc: "Plumbers install and repair pipes and plumbing fixtures in residential, commercial, and industrial settings. Master plumber licenses take 4–10 years to obtain depending on state and dramatically increase earning potential — self-employed master plumbers in major markets often earn six figures.",
  },
  {
    slug: 'hvac-technician',
    title: 'HVAC Technician',
    category: 'Trades',
    medianSalary: 61940,
    p25Salary: 46000,
    p75Salary: 82000,
    p90Salary: 103000,
    entryLevel: 36000,
    seniorLevel: 92000,
    topStates: ['alaska', 'hawaii', 'massachusetts', 'connecticut', 'washington'],
    topCities: ['Seattle', 'Boston', 'New York City'],
    jobGrowth: 9,
    education: '6-month to 2-year technical certificate; EPA 608 refrigerant certification required',
    desc: "HVAC technicians install, maintain, and repair heating, ventilation, air conditioning, and refrigeration systems. The transition to heat pump technology and smart building systems has expanded the technical complexity and earning potential of the role over the past decade.",
  },
  {
    slug: 'carpenter',
    title: 'Carpenter',
    category: 'Trades',
    medianSalary: 57720,
    p25Salary: 43000,
    p75Salary: 79000,
    p90Salary: 102000,
    entryLevel: 34000,
    seniorLevel: 88000,
    topStates: ['alaska', 'hawaii', 'illinois', 'minnesota', 'washington'],
    topCities: ['Seattle', 'Chicago', 'New York City'],
    jobGrowth: 5,
    education: '3–4 year apprenticeship; no license required in most states',
    desc: "Carpenters construct and repair wood-framed structures, finish interiors, and install fixtures across residential and commercial construction. Union carpenters in high-cost markets and finish carpenters specializing in custom millwork and cabinetry earn the highest wages in the trade.",
  },
  {
    slug: 'welder',
    title: 'Welder',
    category: 'Trades',
    medianSalary: 50990,
    p25Salary: 38000,
    p75Salary: 67000,
    p90Salary: 85000,
    entryLevel: 32000,
    seniorLevel: 78000,
    topStates: ['alaska', 'wyoming', 'louisiana', 'hawaii', 'indiana'],
    topCities: ['Houston', 'Dallas', 'Seattle'],
    jobGrowth: 3,
    education: 'Postsecondary certificate from vocational school or community college; AWS certifications add value',
    desc: "Welders join metals using various fusion techniques across construction, manufacturing, shipbuilding, and pipeline installation. Underwater welders and pipeline welders in hazardous environments command wages well above the BLS median, and offshore oil rig welders can earn $100,000 or more annually.",
  },
  {
    slug: 'auto-mechanic',
    title: 'Auto Mechanic',
    category: 'Trades',
    medianSalary: 51840,
    p25Salary: 38000,
    p75Salary: 70000,
    p90Salary: 90000,
    entryLevel: 30000,
    seniorLevel: 80000,
    topStates: ['alaska', 'california', 'washington', 'hawaii', 'connecticut'],
    topCities: ['Los Angeles', 'Seattle', 'San Francisco'],
    jobGrowth: 2,
    education: 'Postsecondary certificate; ASE certifications required by most employers',
    desc: "Auto mechanics diagnose and repair automobiles across dealerships, independent shops, and fleet maintenance operations. Electric vehicle specialization has emerged as the fastest-growing skill premium in the field, with EV-certified technicians earning substantially more than gas-engine-only counterparts.",
  },
  {
    slug: 'construction-manager',
    title: 'Construction Manager',
    category: 'Trades',
    medianSalary: 104900,
    p25Salary: 79000,
    p75Salary: 140000,
    p90Salary: 185000,
    entryLevel: 62000,
    seniorLevel: 160000,
    topStates: ['new-jersey', 'new-york', 'california', 'connecticut', 'alaska'],
    topCities: ['New York City', 'San Francisco', 'Los Angeles'],
    jobGrowth: 8,
    education: "Bachelor's in Construction Management or Civil Engineering; PMP helpful",
    desc: "Construction managers oversee building projects from groundbreaking to completion, coordinating contractors, budgets, schedules, and regulatory compliance. Data center construction and large-scale infrastructure projects under the IIJA represent the highest-demand specializations through 2030.",
  },
  {
    slug: 'elevator-technician',
    title: 'Elevator Technician',
    category: 'Trades',
    medianSalary: 99640,
    p25Salary: 76000,
    p75Salary: 130000,
    p90Salary: 162000,
    entryLevel: 55000,
    seniorLevel: 145000,
    topStates: ['new-york', 'illinois', 'california', 'new-jersey', 'connecticut'],
    topCities: ['New York City', 'Chicago', 'San Francisco'],
    jobGrowth: 4,
    education: '4-year NEIEP apprenticeship; state elevator mechanic license required',
    desc: "Elevator technicians install, maintain, and repair elevators, escalators, and other vertical transportation systems. The IBEW Local 3 agreement in New York City makes elevator mechanics among the highest-earning tradespeople in the country, with journeymen earning over $100 per hour in total compensation.",
  },

  // Creative/Media
  {
    slug: 'graphic-designer',
    title: 'Graphic Designer',
    category: 'Creative',
    medianSalary: 58370,
    p25Salary: 43000,
    p75Salary: 77000,
    p90Salary: 102000,
    entryLevel: 36000,
    seniorLevel: 88000,
    topStates: ['california', 'new-york', 'massachusetts', 'washington', 'connecticut'],
    topCities: ['New York City', 'San Francisco', 'Los Angeles'],
    jobGrowth: 3,
    education: "Bachelor's in Graphic Design or Visual Communications; portfolio required",
    desc: "Graphic designers create visual concepts for marketing materials, websites, product packaging, and brand identity systems. Art directors at advertising agencies and in-house brand teams at major companies earn considerably more than the BLS median, which skews lower due to the high proportion of freelancers.",
  },
  {
    slug: 'copywriter',
    title: 'Copywriter',
    category: 'Creative',
    medianSalary: 72060,
    p25Salary: 52000,
    p75Salary: 100000,
    p90Salary: 140000,
    entryLevel: 40000,
    seniorLevel: 120000,
    topStates: ['new-york', 'california', 'illinois', 'massachusetts', 'washington'],
    topCities: ['New York City', 'San Francisco', 'Chicago'],
    jobGrowth: -2,
    education: "Bachelor's in English, Journalism, or Communications; portfolio required",
    desc: "Copywriters craft persuasive content for advertising, email marketing, websites, and brand communications. The rise of AI writing tools has created headwinds for entry-level copywriting roles, while experienced copywriters with strong strategic thinking and conversion expertise remain highly valued.",
  },
  {
    slug: 'journalist',
    title: 'Journalist',
    category: 'Creative',
    medianSalary: 55960,
    p25Salary: 38000,
    p75Salary: 80000,
    p90Salary: 115000,
    entryLevel: 30000,
    seniorLevel: 95000,
    topStates: ['new-york', 'california', 'illinois', 'district-of-columbia', 'massachusetts'],
    topCities: ['New York City', 'Washington DC', 'Los Angeles'],
    jobGrowth: -3,
    education: "Bachelor's in Journalism or Communications; beat expertise increasingly valued",
    desc: "Journalists research and report news stories for print, broadcast, digital, and podcast outlets. Print newsroom employment has declined sharply since 2005, while digital media, podcasting, and specialized financial journalism — Bloomberg, Reuters, financial trade publications — maintain stronger compensation levels.",
  },
  {
    slug: 'social-media-manager',
    title: 'Social Media Manager',
    category: 'Creative',
    medianSalary: 67080,
    p25Salary: 48000,
    p75Salary: 92000,
    p90Salary: 125000,
    entryLevel: 38000,
    seniorLevel: 110000,
    topStates: ['california', 'new-york', 'illinois', 'washington', 'texas'],
    topCities: ['New York City', 'Los Angeles', 'Chicago'],
    jobGrowth: 6,
    education: "Bachelor's in Marketing, Communications, or related field; platform-specific certifications valuable",
    desc: "Social media managers develop content strategies, manage brand accounts, and analyze engagement across platforms for companies and public figures. The creator economy has expanded the role into influencer partnership management and paid social advertising expertise, with compensation highest at DTC consumer brands and agencies.",
  },
  {
    slug: 'web-designer',
    title: 'Web Designer',
    category: 'Creative',
    medianSalary: 81390,
    p25Salary: 59000,
    p75Salary: 108000,
    p90Salary: 140000,
    entryLevel: 44000,
    seniorLevel: 120000,
    topStates: ['california', 'washington', 'new-york', 'massachusetts', 'colorado'],
    topCities: ['San Francisco', 'Seattle', 'New York City'],
    jobGrowth: 16,
    education: "Bachelor's or Associate's in Web Design; portfolio required; UX skills increasingly important",
    desc: "Web designers create the visual layouts, user interfaces, and interactive experiences for websites and digital applications, increasingly working within design systems using tools like Figma. The overlap with UX design has pushed the discipline toward higher-paying product design roles at technology companies.",
  },
  {
    slug: 'game-developer',
    title: 'Game Developer',
    category: 'Creative',
    medianSalary: 108000,
    p25Salary: 80000,
    p75Salary: 145000,
    p90Salary: 190000,
    entryLevel: 60000,
    seniorLevel: 162000,
    topStates: ['california', 'washington', 'texas', 'illinois', 'georgia'],
    topCities: ['Los Angeles', 'Seattle', 'Austin'],
    jobGrowth: 8,
    education: "Bachelor's in Computer Science or Game Design; portfolio and shipped titles critical",
    desc: "Game developers create video games across gameplay programming, engine development, graphics, AI systems, and tooling. Major studios like Activision Blizzard, EA, and Riot Games pay competitive software engineer salaries, while indie game development skews far lower due to small team economics.",
  },

  // Other
  {
    slug: 'pilot',
    title: 'Commercial Airline Pilot',
    category: 'Transportation',
    medianSalary: 202180,
    p25Salary: 130000,
    p75Salary: 309000,
    p90Salary: 400000,
    entryLevel: 55000,
    seniorLevel: 380000,
    topStates: ['texas', 'georgia', 'illinois', 'california', 'virginia'],
    topCities: ['Dallas', 'Atlanta', 'Chicago'],
    jobGrowth: 4,
    education: 'ATP certificate; 1,500 flight hours minimum; airline-specific training',
    desc: "Commercial airline pilots fly passengers on scheduled routes for major and regional carriers, with Delta, American, and United captains earning over $300,000 annually after reaching senior positions. Entry-level regional airline pay starts around $55,000, requiring 10+ years to reach the major airline salary levels.",
  },
  {
    slug: 'real-estate-agent',
    title: 'Real Estate Agent',
    category: 'Real Estate',
    medianSalary: 56130,
    p25Salary: 32000,
    p75Salary: 100000,
    p90Salary: 175000,
    entryLevel: 25000,
    seniorLevel: 150000,
    topStates: ['california', 'new-york', 'florida', 'texas', 'washington'],
    topCities: ['Los Angeles', 'New York City', 'Miami'],
    jobGrowth: 3,
    education: 'Real estate license (pre-licensing course + state exam); no degree required',
    desc: "Real estate agents facilitate property transactions, earning commission-based income that varies dramatically with local market conditions and individual deal volume. California luxury market agents selling $3M+ homes earn multiples of the BLS median, while agents in slow markets may earn far below it.",
  },
  {
    slug: 'social-worker',
    title: 'Social Worker',
    category: 'Social Services',
    medianSalary: 58380,
    p25Salary: 44000,
    p75Salary: 77000,
    p90Salary: 100000,
    entryLevel: 36000,
    seniorLevel: 85000,
    topStates: ['california', 'new-jersey', 'hawaii', 'district-of-columbia', 'connecticut'],
    topCities: ['San Francisco', 'New York City', 'Los Angeles'],
    jobGrowth: 7,
    education: "Bachelor's in Social Work (BSW) for entry; MSW required for clinical licensure",
    desc: "Social workers help individuals and families navigate mental health challenges, housing instability, domestic violence, and substance abuse, with licensed clinical social workers (LCSWs) providing psychotherapy in private practice. The public sector — county and state agencies — employs the majority but pays less than private clinical practice.",
  },
  {
    slug: 'chef',
    title: 'Chef / Head Cook',
    category: 'Food Service',
    medianSalary: 62090,
    p25Salary: 44000,
    p75Salary: 90000,
    p90Salary: 130000,
    entryLevel: 34000,
    seniorLevel: 110000,
    topStates: ['new-york', 'california', 'hawaii', 'connecticut', 'illinois'],
    topCities: ['New York City', 'Los Angeles', 'Chicago'],
    jobGrowth: 8,
    education: 'Culinary school certificate or degree; formal apprenticeship with established chef',
    desc: "Chefs and head cooks oversee kitchen operations, develop menus, and manage culinary teams in restaurants, hotels, and catering operations. Executive chefs at Michelin-starred restaurants and private household chefs for high-net-worth individuals earn significantly above the BLS median.",
  },
  {
    slug: 'police-officer',
    title: 'Police Officer',
    category: 'Public Safety',
    medianSalary: 74910,
    p25Salary: 56000,
    p75Salary: 99000,
    p90Salary: 125000,
    entryLevel: 42000,
    seniorLevel: 105000,
    topStates: ['california', 'new-jersey', 'alaska', 'washington', 'illinois'],
    topCities: ['San Jose', 'San Francisco', 'New York City'],
    jobGrowth: 3,
    education: 'High school diploma minimum; college degree preferred by many departments; police academy required',
    desc: "Police officers enforce laws, respond to emergencies, and maintain public order for municipal, county, state, and federal agencies. California law enforcement consistently tops national rankings — LAPD officers with 5+ years earn over $100,000 base — while rural departments pay considerably less.",
  },
  {
    slug: 'firefighter',
    title: 'Firefighter',
    category: 'Public Safety',
    medianSalary: 58290,
    p25Salary: 43000,
    p75Salary: 82000,
    p90Salary: 106000,
    entryLevel: 36000,
    seniorLevel: 90000,
    topStates: ['california', 'new-jersey', 'washington', 'alaska', 'connecticut'],
    topCities: ['San Jose', 'San Francisco', 'Seattle'],
    jobGrowth: 4,
    education: 'High school diploma; EMT certification required; Fire Academy training',
    desc: "Firefighters respond to fires, accidents, and medical emergencies while conducting community prevention programs. California's combination of high cost of living, strong unions, and high fire risk has pushed San Jose firefighter base salaries above $130,000, the highest in the nation.",
  },
  {
    slug: 'truck-driver',
    title: 'Truck Driver (CDL)',
    category: 'Transportation',
    medianSalary: 54320,
    p25Salary: 41000,
    p75Salary: 73000,
    p90Salary: 95000,
    entryLevel: 35000,
    seniorLevel: 82000,
    topStates: ['alaska', 'north-dakota', 'wyoming', 'washington', 'nevada'],
    topCities: ['Dallas', 'Chicago', 'Houston'],
    jobGrowth: 4,
    education: 'Commercial Driver\'s License (CDL); 6-8 week training program at minimum',
    desc: "Truck drivers haul freight across local, regional, and long-haul routes, with owner-operators and specialized hazmat and oversized load drivers earning substantially above the median. The e-commerce logistics boom has maintained strong demand despite automation concerns around autonomous trucking.",
  },
  {
    slug: 'personal-trainer',
    title: 'Personal Trainer',
    category: 'Fitness',
    medianSalary: 46480,
    p25Salary: 32000,
    p75Salary: 66000,
    p90Salary: 92000,
    entryLevel: 25000,
    seniorLevel: 80000,
    topStates: ['california', 'new-york', 'connecticut', 'massachusetts', 'colorado'],
    topCities: ['New York City', 'Los Angeles', 'San Francisco'],
    jobGrowth: 14,
    education: 'NASM, ACE, or NSCA certification; no degree required; CPR/AED required',
    desc: "Personal trainers design individualized exercise programs and coach clients toward fitness goals in gyms, studios, and private settings. Trainers in luxury Manhattan gyms charging $200+ per session operate at an entirely different economic level than the BLS median suggests.",
  },
  {
    slug: 'event-planner',
    title: 'Event Planner',
    category: 'Hospitality',
    medianSalary: 63140,
    p25Salary: 44000,
    p75Salary: 85000,
    p90Salary: 115000,
    entryLevel: 35000,
    seniorLevel: 95000,
    topStates: ['new-york', 'california', 'district-of-columbia', 'connecticut', 'massachusetts'],
    topCities: ['New York City', 'Los Angeles', 'Washington DC'],
    jobGrowth: 8,
    education: "Bachelor's in Hospitality Management or Business; CMP designation valued",
    desc: "Event planners coordinate weddings, conferences, conventions, and corporate events — managing venues, vendors, budgets, and logistics. Corporate event planners at major companies and luxury wedding planners in high-end markets represent the highest-earning segments of the profession.",
  },
  {
    slug: 'nutritionist',
    title: 'Registered Dietitian / Nutritionist',
    category: 'Healthcare',
    medianSalary: 73910,
    p25Salary: 59000,
    p75Salary: 92000,
    p90Salary: 115000,
    entryLevel: 50000,
    seniorLevel: 100000,
    topStates: ['california', 'new-jersey', 'connecticut', 'alaska', 'massachusetts'],
    topCities: ['San Francisco', 'New York City', 'Los Angeles'],
    jobGrowth: 7,
    education: "Bachelor's and supervised practice; RD credential requires national exam; Master's increasingly required",
    desc: "Registered dietitians provide medical nutrition therapy and counseling for patients in hospitals, clinics, and private practice. Sports dietitians for professional teams, corporate wellness dietitians at tech companies, and eating disorder specialists represent the highest-paying practice settings.",
  },
]

export function getProfessionBySlug(slug: string): ProfessionData | undefined {
  return PROFESSIONS.find((p) => p.slug === slug)
}

export const PROFESSION_CATEGORIES = [...new Set(PROFESSIONS.map((p) => p.category))]
